language: node_js
node_js:
    - '10'
# script:
#     - npm run test
before_deploy:
    - git push --tags
deploy:
    provider: npm
    email: '$NPM_EMAIL'
    api_key: '$NPM_API_TOKEN'
    skip_cleanup: true
    on:
        branch: release
